LOGGER_OUT:=logger.o
NEG_SRC_OUT:=negative.o 
BRIGHT_SRC_OUT:=bright.o

NEG_PROCESS:=neg
BRIGHT_PROCESS:=bri

LOGGER_SRC:=logger.c
NEG_SRC:=negative_convert.c
LOGGER_HEADER:=logger.h
PREPROCESSING_HEADER:=processing.h
BRIGHT_SRC:=bright_convert.c
MAIN_RUN:=run.c


$(LOGGER_OUT):	$(LOGGER_SRC)
		gcc -c $(LOGGER_SRC) -o $(LOGGER_OUT)
$(NEG_SRC_OUT):	$(NEG_SRC) $(LOGGER_OUT) $(LOGGER_HEADER)
		gcc -c $(NEG_SRC) -o $(NEG_SRC_OUT)
$(BRIGHT_SRC_OUT): $(BRIGHT_SRC) $(LOGGER_OUT) $(LOGGER_HEADER)
		gcc -c $(BRIGHT_SRC) -o $(BRIGHT_SRC_OUT)

$(NEG_PROCESS):	$(NEG_SRC) $(LOGGER_OUT) $(LOGGER_HEADER)
		gcc -Wall -o $(NEG_PROCESS) $(NEG_SRC) $(LOGGER_OUT)

$(BRIGHT_PROCESS):	$(BRIGHT_SRC) $(LOGGER_OUT) $(LOGGER_HEADER)
		gcc -Wall -o $(BRIGHT_PROCESS) $(BRIGHT_SRC) $(LOGGER_OUT)

install:	$(MAIN_RUN) $(LOGGER_OUT) $(NEG_SRC_OUT) $(BRIGHT_SRC_OUT) $(LOGGER_HEADER) $(NEG_SRC) $(BRIGHT_SRC)
		gcc -Wall -o image-pipe	$(MAIN_RUN) $(LOGGER_OUT) $(NEG_SRC_OUT) $(BRIGHT_SRC_OUT)

clean:
	rm $(LOGGER_OUT) $(NEG_SRC_OUT) $(BRIGHT_SRC_OUT) image-pipe
